---
title: "Iceland's energy production and consumption (1940-2020)"
author: "Markos"
format: html
editor: visual
---

# Introduction

```{r}
# Load packages
# install.packages('pxweb')
# install.packages('janitor')
library(pxweb)
library(tidyverse)
library(readxl)
library(janitor)
```

```{r get-data-from-api}
# Save download link for data set

# I first run the code below. This creates a series of questions answerable by
# typing different symbols. Once I go through all the steps, the functions 
# prints all the commands needed to send a query and fetch the data.
# pxweb_get_data("https://px.hagstofa.is:443/pxen/api/v1/en/Umhverfi/4_orkumal/2_framleidslaognotkun/IDN02102.px")

# PXWEB query 
pxweb_query_list <- 
  list("Year"=c("1940","1941","1942","1943","1944","1945","1946","1947","1948","1949","1950","1951","1952","1953","1954","1955","1956","1957","1958","1959","1960","1961","1962","1963","1964","1965","1966","1967","1968","1969","1970","1971","1972","1973","1974","1975","1976","1977","1978","1979","1980","1981","1982","1983","1984","1985","1986","1987","1988","1989","1990","1991","1992","1993","1994","1995","1996","1997","1998","1999","2000","2001","2002","2003","2004","2005","2006","2007","2008","2009","2010","2011","2012","2013","2014","2015","2016","2017","2018","2019","2020"),
       "Unit"=c("0","1"),
       "Type"=c("HYDRO","GEOTHERMAL","WIND","OIL","COAL","PEAT","RENEWABLE","TOTAL","TOTAL_NATIONAL","TOTAL_IMPORT"))

# Download data 
px_data <- 
  pxweb_get(url = "https://px.hagstofa.is:443/pxen/api/v1/en/Umhverfi/4_orkumal/2_framleidslaognotkun/IDN02102.px",
            query = pxweb_query_list)

# Convert to data.frame 
px_data_frame <- as.data.frame(px_data, column.name.type = "text", variable.value.type = "text")

# # Get pxweb data comments 
# px_data_comments <- pxweb_data_comments(px_data)
# px_data_comments_df <- as.data.frame(px_data_comments)
# 
# # Cite the data as 
# pxweb_cite(px_data)

# Rename data frame
isl_energy <- px_data_frame

# Remove all other objects
rm(d, px_data, px_data_comments, px_data_frame, pxweb_query_list)
```

Now that I have the data saved as an object called 'isl_energy', I look at its structure.

```{r glimpse-data-frame}
# Get first view of the data
glimpse(isl_energy)
```

```{r}
# Clean column names using 'janitor' package
isl_energy <- isl_energy %>% clean_names() # `Gross energy consumption by source` becomes gross_energy_consumption_by_source
```
